# ----- Libraries needed for auto-generated code ----- #
library(jsonlite)
library(httr)
library(readr)
# ----- End of libraries ----- #

require(Rcpp)
sourceCpp("source.cpp")
system.time(
#     rec <- est_bc_source(dat.bc.t)
# ----- THIS CODE IS AUTO-GENERATED BY MULTICONTAINERIZER ----- #
{# Convert each param to JSON format
json_geno <- toJSON(as.matrix(dat.bc.t))

# Prepare a list for JSON conversion
list_rec <- list(
	geno = json_geno
)
# Convert to JSON format
json_rec <- toJSON(list_rec, auto_unbox=TRUE)
# URL dependent on configuration
url_rec <- "http://localhost:8080/est_bc_source"

# Call the correct API endpoint for this function and process the result
response_rec <- POST(
	url_rec,
	body = json_rec,
	encode = "raw",
	add_headers("Content-Type" = "application/json")
)

content_rec <- content(response_rec)

# Capture the results in the original variable, and convert into correct format
rec <- do.call(rbind, as.matrix(content_rec))
rec <- matrix(as.numeric(rec), nrow = nrow(rec), ncol = ncol(rec))
}# ---- END OF AUTO-GENERATED CODE ----- #
)
choose(5000, 2)
image.plot(rec, col=rev(tim.colors()))